from tkinter import *
top = Tk()
lb1 = Listbox(top)
lb1.insert(1, "Python")
lb1.insert(2, "Perl")
lb1.insert(3, "C")
lb1.insert(4, "C++")
lb1.insert(5, "Java")
lb1.insert(6, "JavaScript")
lb1.insert(7, "Ruby")
lb1.pack()
top.mainloop()
